name:                yalc
version:             0.1.0.0
github:              "kellino/yalc"
license:             BSD3
author:              "David Kelly"
maintainer:          "david.kelly.15@ucl.ac.uk"
copyright:           "2019 David Kelly"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/kellino/yalc#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  yalc:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - megaparsec >= 7.0.4
    - parser-combinators >= 1.0.0
    - unbound-generics >= 0.4.0
    - mtl >= 2.2.2
    - containers >= 0.6.0.1
    - pretty >= 1.1.3.6
    - text >= 1.2.3.1
